version: '3.7'
services:
  postgres-db:
    container_name: postgresdb    
    image: postgres:alpine
    networks:
      - sonar-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql/data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
  sonar-service:
    container_name: sonarqube
    depends_on:
      - postgres-db
      - elasticsearch-service
    image: sonarqube:9.3.0-community
    networks:
      - sonar-network    
    ports:
      - 9092:9092
      - 9000:9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube/temp:/opt/sonarqube/temp
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 640M
networks:
  sonar-network:
    driver: bridge
    driver_opts:
            com.docker.network.enable_ipv6: "true"
    ipam:
        driver: default
